import { NavigationConfig, WhatScienceMenuItem } from '@/types/navigation'

// Translation keys mapping
const navTranslations: Record<string, Record<string, string>> = {
  en: {
    'What science can do': 'What science can do',
    'Home': 'Home',
    'About Us': 'About Us',
    'Manufacturing': 'Manufacturing',
    'R&D Innovation': 'R&D Innovation',
    'Quality & Compliance': 'Quality & Compliance',
    'Products': 'Products',
    'News': 'News',
    'Careers': 'Careers',
    'Contact': 'Contact',
    'Resources': 'Resources',
    'Overview': 'Overview',
    'Stories of impact': 'Stories of impact',
    'Publications': 'Publications',
    'Softgels': 'Softgels',
    'Tablets': 'Tablets',
    'Creams & Ointments': 'Creams & Ointments',
    'Injections': 'Injections',
  },
  lo: {
    'What science can do': 'ສິ່ງທີ່ວິທະຍາສາດເຮັດໄດ້',
    'Home': 'ໜ້າຫຼັກ',
    'About Us': 'ກ່ຽວກັບພວກເຮົາ',
    'Manufacturing': 'ການຜະລິດ',
    'R&D Innovation': 'ນະວັດຕະກຳ R&D',
    'Quality & Compliance': 'ຄຸນນະພາບ ແລະ ການປະຕິບັດຕາມ',
    'Products': 'ຜະລິດຕະພັນ',
    'News': 'ຂ່າວສານ',
    'Careers': 'ອາຊີບ',
    'Contact': 'ຕິດຕໍ່',
    'Resources': 'ຊັບພະຍາກອນ',
    'Overview': 'ພາບລວມ',
    'Stories of impact': 'ເລື່ອງລາວຜົນກະທົບ',
    'Publications': 'ສິ່ງພິມ',
    'Softgels': 'ແຄບຊູນອ່ອນ',
    'Tablets': 'ຢາເມັດ',
    'Creams & Ointments': 'ຄີມ ແລະ ຢາທາ',
    'Injections': 'ຢາສັກ',
  },
  th: {
    'What science can do': 'สิ่งที่วิทยาศาสตร์ทำได้',
    'Home': 'หน้าแรก',
    'About Us': 'เกี่ยวกับเรา',
    'Manufacturing': 'การผลิต',
    'R&D Innovation': 'นวัตกรรม R&D',
    'Quality & Compliance': 'คุณภาพและการปฏิบัติตาม',
    'Products': 'ผลิตภัณฑ์',
    'News': 'ข่าวสาร',
    'Careers': 'ร่วมงานกับเรา',
    'Contact': 'ติดต่อเรา',
    'Resources': 'แหล่งข้อมูล',
    'Overview': 'ภาพรวม',
    'Stories of impact': 'เรื่องราวแห่งความเปลี่ยนแปลง',
    'Publications': 'สิ่งพิมพ์',
    'Softgels': 'ซอฟท์เจล',
    'Tablets': 'ยาเม็ด',
    'Creams & Ointments': 'ครีมและขี้ผึ้ง',
    'Injections': 'ยาฉีด',
  },
  vi: {
    'What science can do': 'Khoa học có thể làm gì',
    'Home': 'Trang chủ',
    'About Us': 'Giới thiệu',
    'Manufacturing': 'Sản xuất',
    'R&D Innovation': 'Đổi mới R&D',
    'Quality & Compliance': 'Chất lượng & Tuân thủ',
    'Products': 'Sản phẩm',
    'News': 'Tin tức',
    'Careers': 'Tuyển dụng',
    'Contact': 'Liên hệ',
    'Resources': 'Tài nguyên',
    'Overview': 'Tổng quan',
    'Stories of impact': 'Câu chuyện tác động',
    'Publications': 'Ấn phẩm',
    'Softgels': 'Viên nang mềm',
    'Tablets': 'Viên nén',
    'Creams & Ointments': 'Kem & Thuốc mỡ',
    'Injections': 'Thuốc tiêm',
  },
  ar: {
    'What science can do': 'ما يمكن أن يفعله العلم',
    'Home': 'الرئيسية',
    'About Us': 'من نحن',
    'Manufacturing': 'التصنيع',
    'R&D Innovation': 'الابتكار والبحث',
    'Quality & Compliance': 'الجودة والامتثال',
    'Products': 'المنتجات',
    'News': 'الأخبار',
    'Careers': 'الوظائف',
    'Contact': 'اتصل بنا',
    'Resources': 'الموارد',
    'Overview': 'نظرة عامة',
    'Stories of impact': 'قصص التأثير',
    'Publications': 'المنشورات',
    'Softgels': 'كبسولات هلامية',
    'Tablets': 'أقراص',
    'Creams & Ointments': 'كريمات ومراهم',
    'Injections': 'حقن',
  },
  es: {
    'What science can do': 'Lo que la ciencia puede hacer',
    'Home': 'Inicio',
    'About Us': 'Sobre nosotros',
    'Manufacturing': 'Fabricación',
    'R&D Innovation': 'Innovación I+D',
    'Quality & Compliance': 'Calidad y Cumplimiento',
    'Products': 'Productos',
    'News': 'Noticias',
    'Careers': 'Empleo',
    'Contact': 'Contacto',
    'Resources': 'Recursos',
    'Overview': 'Descripción general',
    'Stories of impact': 'Historias de impacto',
    'Publications': 'Publicaciones',
    'Softgels': 'Cápsulas blandas',
    'Tablets': 'Comprimidos',
    'Creams & Ointments': 'Cremas y Ungüentos',
    'Injections': 'Inyecciones',
  },
  pt: {
    'What science can do': 'O que a ciência pode fazer',
    'Home': 'Início',
    'About Us': 'Sobre nós',
    'Manufacturing': 'Fabricação',
    'R&D Innovation': 'Inovação em P&D',
    'Quality & Compliance': 'Qualidade e Conformidade',
    'Products': 'Produtos',
    'News': 'Notícias',
    'Careers': 'Carreiras',
    'Contact': 'Contato',
    'Resources': 'Recursos',
    'Overview': 'Visão geral',
    'Stories of impact': 'Histórias de impacto',
    'Publications': 'Publicações',
    'Softgels': 'Softgels',
    'Tablets': 'Comprimidos',
    'Creams & Ointments': 'Cremes e Pomadas',
    'Injections': 'Injeções',
  },
}

export function getNavLabel(key: string, locale: string = 'en'): string {
  return navTranslations[locale]?.[key] || navTranslations['en']?.[key] || key
}

export { navTranslations }

export const navigationConfig: NavigationConfig = {
  items: [
    { 
      label: 'What science can do', 
      href: '/what-science-can-do',
      hasDropdown: true,
      items: [
        { label: 'Overview', href: '/what-science-can-do' },
        { label: 'Stories of impact', href: '/what-science-can-do/stories-of-impact' },
        { label: 'Publications', href: '/what-science-can-do/publications' },
      ]
    },
    { label: 'Home', href: '/' },
    { label: 'About Us', href: '/about' },
    { label: 'Manufacturing', href: '/manufacturing' },
    { label: 'R&D Innovation', href: '/rd-innovation' },
    { label: 'Quality & Compliance', href: '/quality-compliance' },
    { 
      label: 'Products', 
      href: '/products', 
      hasDropdown: true,
      items: [
        { label: 'Overview', href: '/products' },
        { label: 'Softgels', href: '/products?category=softgels' },
        { label: 'Tablets', href: '/products?category=tablets' },
        { label: 'Creams & Ointments', href: '/products?category=creams' },
        { label: 'Injections', href: '/products?category=injections' },
      ]
    },
    { label: 'News', href: '/news' },
    { label: 'Careers', href: '/careers' },
    { label: 'Contact', href: '/contact' },
    { label: 'Resources', href: '/resources' },
  ],
  ctaButtons: {
    verify: { label: 'Verify', href: '/verify' },
    orderNow: { label: 'Order Now', href: '/order-now' },
    aiAssistant: { label: 'AI Assistant', href: '/ai-assistant' },
  },
  language: {
    default: 'en',
    options: [
      { code: 'en', label: 'English' },
      { code: 'lo', label: 'ລາວ' },
      { code: 'th', label: 'ไทย' },
      { code: 'vi', label: 'Tiếng Việt' },
      { code: 'ar', label: 'العربية' },
      { code: 'es', label: 'Español' },
      { code: 'pt', label: 'Português' },
    ]
  }
}

export const whatScienceMenuItems: WhatScienceMenuItem[] = [
  { 
    label: 'What science can do', 
    href: '/what-science-can-do',
    description: 'Exploring the frontiers of pharmaceutical science and innovation'
  },
  { 
    label: 'Stories of impact', 
    href: '/what-science-can-do/stories-of-impact',
    description: 'Real-world impact of our research and partnerships'
  },
  { 
    label: 'Publications', 
    href: '/what-science-can-do/publications',
    description: 'Scientific publications, research papers and findings'
  },
]
